/* use with  xibetagenomic.cpp */
extern const unsigned samplesize ;
extern const unsigned lgroups ;
extern const unsigned Imin ;
extern const unsigned Imax ;
extern const unsigned Jmin ;
extern const unsigned Jmax ;
extern const unsigned Kmin ;
extern const unsigned Kmax ;
extern const unsigned trials ;
